### ISSUE TITLE
Comments don't prevent increasing indentation level

### ISSUE THREAD

**Issue by rcfox** [skeeto/psl-mode#2]
The first example from http://www.cs.brown.edu/courses/cs173/2012/Assignments/ParselTest/tutorial.html has comments that contain "defvar" and "deffun" which incorrectly increase the indentation levels.

**Comment by skeeto** [comment]
Oops, I thought I replied to this issue back when it fixed it. Anyway, this should be fixed in fda7d53c23f464b274d2511f777487d070aae5ea (or about so).
